### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by silicakes** [Thunberg087/vue-fragment#56]
Hi,
I'd like to use this in my company's code but am limited with the types of licenses I can utilize.

Could you please add a license for this library? (preferably MIT; \*wink, wink\*)

Thanks!

**Comment by OmgImAlexis** [comment]
https://github.com/Thunberg087/vue-fragment/blob/master/package.json#L24

**Comment by silicakes** [comment]
> https://github.com/Thunberg087/vue-fragment/blob/master/package.json#L24

Thanks @OmgImAlexis! didn't think about looking over there.

FYI: There's also an option to add it to the repo itself (through the projects settings)

**Comment by OmgImAlexis** [comment]
I would have expected this to auto-set the license field in the repo like a LICENSE file does. Sounds like a Github bug.
